### ISSUE TITLE
Support for MSP430G2231

### ISSUE THREAD

**Issue by Tinker321** [abhra0897/MSP430-CC1101-Energia-Library#1]
Hello! 
First of all, thanks for making the CC1101 library available for so many models of MSP430.
I tried to use use the library with MSP430 Launchpad (with MSP430G2231), but with no success.
I also tried to modify the "pins.h"-file so that the pinout should match G2231, but I probably did something wrong and it didn't work.

I would seek assistance with getting the CC1101 working with G2231 model of MSP430. Is modifying the pins.h enough or are there other modifications that would have to be made?

Please keep the instructions simple, as I am a true beginner with the microcontroller scene.

**Comment by abhra0897** [comment]
Hi, the library mostly works with G2x53 and G2x13 series MCUs. Just by changing the SPI pins for MSP430G2231, it won't work.

Why? Becauae the SPI settings should be reconfigured as per the registers specified in the user manual.

SPI_INIT(), SPI_WRITE_BYTE(), and SPI_READ_BYTE() macros should be changed as per your MCU. Maybe other register settings should be changed too. 

Please study the datasheet and user manual of G2231 and find out how to configure SPI, read and write byte using SPI.
Also try to find some examples. 

I'll try to add support for G2231 in near future but as I don't have that MCU, I can't gurantee its success.

Regards, 
Avra

**Comment by abhra0897** [comment]
Hi Tinker321,
This library is discontinued from today as I have developed a much better library (v2). (https://github.com/cc1101_msp430_energia_v2).

So, here I'm closing the issue. Please keep an eye on the newer library as I'm going to add support for MSP430G2231 soon.
